import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import ClientLoader from "@/components/ClientLoader"; // Import the client loader component
import Navbar from "@/components/Navbar";
import ClientProvider from "@/redux/ClientProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProvider>
          <Navbar />
          <ClientLoader>
            {children} {/* Render children wrapped in ClientLoader */}
          </ClientLoader>
        </ClientProvider>
      </body>
    </html>
  );
}
